default:
  version: 1
  formatters:
    standard:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    detailed:
      format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: logs/training.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
  loggers:
    math_reasoning:  # Root logger for our project
      level: DEBUG
      handlers: [console, file]
      propagate: false 